version: '3'

services:
  humaninfoapplication:
    build:
      context: ./HumanInfoApplication
      args:
        URL: "http://secondapplication:80"
    ports:
      - 7215:80
    volumes:
      - '/HumanInfoApplication/app'
    networks:
      - common
  
  secondapplication:
    build: ./SecondApplication
    ports:
      - 7149:80
    volumes:
      - '/SecondApplication/app'
    networks:
      - common
networks:
  common: