version: '3'

services:
  humaninfoapplication:
    build:
      context: ./HumanInfoApplication
      args:
        URL: "http://SecondApplication:7149"
    ports:
      - 5001:7215
    volumes:
      - '/HumanInfoApplication/app'
    networks:
      - common
  
  secondapplication:
    build: ./SecondApplication
    volumes:
      - '/SecondApplication/app'
    networks:
      - common
networks:
  common: